# Generated by Django 5.0.1 on 2025-10-05 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatSupervisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertanyaan', models.TextField()),
                ('bobot', models.FloatField(default=1)),
                ('format_supervisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='supervisi.formatsupervisi')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('skor_total', models.FloatField(default=0)),
                ('ttd_perawat', models.ImageField(blank=True, null=True, upload_to='ttd/')),
                ('ttd_kepala', models.ImageField(blank=True, null=True, upload_to='ttd/')),
                ('format_supervisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisi.formatsupervisi')),
                ('kepala_ruangan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisi_kepala', to=settings.AUTH_USER_MODEL)),
                ('perawat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisi_perawat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JawabanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisi.itemformat')),
                ('supervisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban', to='supervisi.supervisi')),
            ],
        ),
    ]
