# Generated by Django 5.1.7 on 2025-10-08 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FormatSupervisi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=255)),
                ("deskripsi", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ItemFormat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pertanyaan", models.TextField()),
                ("bobot", models.FloatField(default=1)),
                (
                    "format_supervisi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="supervisi.formatsupervisi",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AspekFormat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_aspek", models.CharField(max_length=500)),
                ("d", models.BooleanField(default=False)),
                ("td", models.BooleanField(default=False)),
                (
                    "item_format",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aspek",
                        to="supervisi.itemformat",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Supervisi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kepala_nama",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nama Kepala Ruangan (custom)",
                    ),
                ),
                (
                    "kepala_nip",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="NIP Kepala Ruangan (custom)",
                    ),
                ),
                ("tanggal", models.DateField(auto_now_add=True)),
                (
                    "tim",
                    models.IntegerField(
                        choices=[
                            (1, "Tim 1"),
                            (2, "Tim 2"),
                            (3, "Tim 3"),
                            (4, "Tim 4"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "jenjang_pk",
                    models.CharField(
                        choices=[
                            ("PK I", "PK I"),
                            ("PK II", "PK II"),
                            ("PK III", "PK III"),
                            ("PK IV", "PK IV"),
                        ],
                        default="PK I",
                        max_length=20,
                    ),
                ),
                (
                    "ruang",
                    models.CharField(default="Imdad Hamid Lantai 2", max_length=100),
                ),
                ("skor_total", models.FloatField(default=0)),
                (
                    "ttd_perawat",
                    models.ImageField(blank=True, null=True, upload_to="ttd/"),
                ),
                (
                    "ttd_kepala",
                    models.ImageField(blank=True, null=True, upload_to="ttd/"),
                ),
                (
                    "ttd_file",
                    models.ImageField(blank=True, null=True, upload_to="ttd/"),
                ),
                (
                    "format_supervisi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supervisi.formatsupervisi",
                    ),
                ),
                (
                    "kepala_ruangan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervisi_kepala",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "perawat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervisi_perawat",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JawabanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jawaban", models.FloatField()),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supervisi.itemformat",
                    ),
                ),
                (
                    "supervisi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jawaban",
                        to="supervisi.supervisi",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JawabanAspek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("d", models.BooleanField(default=False)),
                ("td", models.BooleanField(default=False)),
                (
                    "aspek",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supervisi.aspekformat",
                    ),
                ),
                (
                    "supervisi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jawaban_aspek",
                        to="supervisi.supervisi",
                    ),
                ),
            ],
        ),
    ]
