# Generated by Django 5.1.7 on 2025-10-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supervisi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supervisi",
            name="perawat_nama",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Nama Perawat (custom)",
            ),
        ),
    ]
