# Generated by Django 5.0.1 on 2025-10-05 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AspekFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_aspek', models.CharField(max_length=500)),
                ('d', models.BooleanField(default=False)),
                ('td', models.BooleanField(default=False)),
                ('item_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspek', to='supervisi.itemformat')),
            ],
        ),
    ]
