# Generated by Django 5.0.1 on 2025-10-05 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisi', '0002_aspekformat'),
    ]

    operations = [
        migrations.CreateModel(
            name='JawabanAspek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d', models.BooleanField(default=False)),
                ('td', models.BooleanField(default=False)),
                ('aspek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisi.aspekformat')),
                ('supervisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban_aspek', to='supervisi.supervisi')),
            ],
        ),
    ]
