# Generated by Django 5.0.1 on 2025-10-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisi', '0003_jawabanaspek'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisi',
            name='ttd_file',
            field=models.ImageField(blank=True, null=True, upload_to='ttd/'),
        ),
    ]
