# Generated by Django 5.0.1 on 2025-10-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisi', '0004_supervisi_ttd_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisi',
            name='jenjang_pk',
            field=models.CharField(choices=[('PK I', 'PK I'), ('PK II', 'PK II'), ('PK III', 'PK III'), ('PK IV', 'PK IV')], default='PK I', max_length=20),
        ),
        migrations.AddField(
            model_name='supervisi',
            name='ruang',
            field=models.CharField(default='Imdad Hamid Lantai 2', max_length=100),
        ),
        migrations.AddField(
            model_name='supervisi',
            name='tim',
            field=models.IntegerField(choices=[(1, 'Tim 1'), (2, 'Tim 2'), (3, 'Tim 3'), (4, 'Tim 4')], default=1),
        ),
    ]
