# Generated by Django 5.1.7 on 2025-10-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supervisi", "0005_supervisi_jenjang_pk_supervisi_ruang_supervisi_tim"),
    ]

    operations = [
        migrations.AddField(
            model_name="supervisi",
            name="kepala_nama",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Nama Kepala Ruangan (custom)",
            ),
        ),
        migrations.AddField(
            model_name="supervisi",
            name="kepala_nip",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="NIP Kepala Ruangan (custom)",
            ),
        ),
    ]
